server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Sin esto, al refrescar /archivos o /usuarios Nginx devuelve 404
    # porque esas rutas no son archivos reales, las maneja React
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;
}
